### ISSUE TITLE
is it secure to host config

### ISSUE THREAD

**Issue by OilFire** [openbullet/openbullet-api#7]
hi, I wanted to know if it's secure to host config here without getting leaked. 

can u pls help me in encrypting it

**Comment by openbullet** [comment]
No it's not secure, anyone with a bit of knowledge is able to forge a request (even with OB itself) to download the entire zip with all configs inside. Even if you encrypt them, since the software is open source, it's easy to just mod it to save the file once it's decrypted in memory, anyone with a bit of coding knowledge will be able to do that.

In addition, OB1 is not supported anymore. Please switch to OB2 which has more features to secure configs as you can read here

https://discourse.openbullet.dev/t/how-to-secure-your-configs/3248
